### ISSUE TITLE
[Request]: advanced-combat-tracker

### ISSUE THREAD

**Issue by superusercode** [Calinou/scoop-games#963]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used
- [X] A game or a game-related tool
- [X] English interface (or at least English documentation)
- [X] Latest stable or development version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

advanced-combat-tracker

### Description

Advanced Combat Tracker is a plugin-extendable MMORPG Log Parser.

### Homepage

https://advancedcombattracker.com

### Download Link(s)

https://github.com/EQAditu/AdvancedCombatTracker/releases/download/3.6.2.279/ACTv3.zip

### Some Indication of Popularity/Repute

https://github.com/EQAditu/AdvancedCombatTracker 112 stars on github
parsing is a pretty major part of high level play in ffxiv, so it's a near constant use for people who runs raids
